### ISSUE TITLE
np.squeeze error: cannot select an axis to squeeze out which has size not equal to one

### ISSUE THREAD

**Issue by YilanWang** [alibaba/TinyNeuralNetwork#198]
您好，我的模型在转为tflite时发现了这个squeeze的问题，请问这个问题是由于模型实现的不规范，由于我们暂时支持有问题导致的呢，如果是模型的问题，请问我如何check这句话对应的model是哪里有问题呢？多谢多谢~

```
Traceback (most recent call last):
  File "/home/alanwang1/xxx/pth2onnx.py", line 107, in <module>
    converter.convert()
  File "/home/alanwang1/anaconda3/envs/openmm/lib/python3.9/site-packages/TinyNeuralNetwork-0.1.0.20230313110728+489448d818acc4002a3842758886423a62b04a04-py3.9.egg/tinynn/converter/base.py", line 476, in convert
    self.init_operations()
  File "/home/alanwang1/anaconda3/envs/openmm/lib/python3.9/site-packages/TinyNeuralNetwork-0.1.0.20230313110728+489448d818acc4002a3842758886423a62b04a04-py3.9.egg/tinynn/converter/base.py", line 439, in init_operations
    converter.parse(node, attrs, args, self.common_graph)
  File "/home/alanwang1/anaconda3/envs/openmm/lib/python3.9/site-packages/TinyNeuralNetwork-0.1.0.20230313110728+489448d818acc4002a3842758886423a62b04a04-py3.9.egg/tinynn/converter/operators/torch/aten.py", line 2995, in parse
    fill_arr = np.squeeze(indices_tensor.tensor.copy().astype(input_tensor.dtype), -1)
  File "<__array_function__ internals>", line 180, in squeeze
  File "/home/alanwang1/anaconda3/envs/openmm/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 1545, in squeeze
    return squeeze(axis=axis)
ValueError: cannot select an axis to squeeze out which has size not equal to one
```

**Comment by peterjc123** [comment]
https://github.com/alibaba/TinyNeuralNetwork/commit/8604654358c9966ffa7ab55f2a0d875c6dc1068f
已经修复
