### ISSUE TITLE
RuntimeError: No such operator prim::DictConstruct

### ISSUE THREAD

**Issue by kraus-yang** [alibaba/TinyNeuralNetwork#200]
The error occurs when convering a pytorch model to tflite
Traceback (most recent call last):
  File "/home/krausyang/Projects/TinyNeuralNetwork/VSR/convert.py", line 95, in <module>
    main_worker()
  File "/home/krausyang/Projects/TinyNeuralNetwork/VSR/convert.py", line 91, in main_worker
    converter.convert()
  File "/home/krausyang/Projects/TinyNeuralNetwork/tinynn/converter/base.py", line 477, in convert
    self.init_operations()
  File "/home/krausyang/Projects/TinyNeuralNetwork/tinynn/converter/base.py", line 440, in init_operations
    converter.parse(node, attrs, args, self.common_graph)
  File "/home/krausyang/Projects/TinyNeuralNetwork/tinynn/converter/operators/torch/base.py", line 737, in parse
    self.run(node)
  File "/home/krausyang/Projects/TinyNeuralNetwork/tinynn/converter/operators/torch/base.py", line 135, in run
    func = torch._C._jit_get_operation(node.kind())
RuntimeError: No such operator prim::DictConstruct

**Comment by peterjc123** [comment]
@kraus-yang Would you please please provide an example for generating this operator?
