### ISSUE TITLE
ERROR (tinynn.converter.base) Unsupported ops: aten::sum

### ISSUE THREAD

**Issue by steven9046** [alibaba/TinyNeuralNetwork#24]
提示不支持这个

**Comment by peterjc123** [comment]
@steven9046 我们这边支持一下，稍等

**Comment by steven9046** [comment]
:thumbsup::thumbsup::thumbsup:

**Comment by steven9046** [comment]
> @steven9046 我们这边支持一下，稍等

:thumbsup::thumbsup::thumbs

**Comment by peterjc123** [comment]
@steven9046 好了，重新安装一下试试

**Comment by steven9046** [comment]
又提示了这个错误:
```
/home/vipuser/miniconda3/lib/python3.8/site-packages/torch/jit/_trace.py:934: TracerWarning: Encountering a list at the output of the tracer might cause the trace to be incorrect, this is only valid if the container structure does not change based on the module's inputs.Consider using a constant container instead (e.g. for `list`, use a `tuple` instead. for `dict`, use a `NamedTuple` instead). If you absolutely need this and know the side effects, pass strict=False to trace() to allow this behavior.
  module._c._create_method_from_trace(
Traceback (most recent call last):
  File "convert.py", line 47, in <module>
    main_worker()
  File "convert.py", line 44, in main_worker
    converter.convert()
  File "/home/vipuser/miniconda3/lib/python3.8/site-packages/TinyNeuralNetwork-0.1.0+02d74089524c0f37c6c5a73e04ce375a65e1d254-py3.8.egg/tinynn/converter/base.py", line 285, in convert
    self.init_operations()
  File "/home/vipuser/miniconda3/lib/python3.8/site-packages/TinyNeuralNetwork-0.1.0+02d74089524c0f37c6c5a73e04ce375a65e1d254-py3.8.egg/tinynn/converter/base.py", line 250, in init_operations
    converter.parse(node, attrs, args, self.common_graph)
  File "/home/vipuser/miniconda3/lib/python3.8/site-packages/TinyNeuralNetwork-0.1.0+02d74089524c0f37c6c5a73e04ce375a65e1d254-py3.8.egg/tinynn/converter/operators/torch/aten.py", line 2067, in parse
    self.handle_reduce(tfl.SumOperator, graph_converter, False)
  File "/home/vipuser/miniconda3/lib/python3.8/site-packages/TinyNeuralNetwork-0.1.0+02d74089524c0f37c6c5a73e04ce375a65e1d254-py3.8.egg/tinynn/converter/operators/torch/base.py", line 398, in handle_reduce
    self.output_tensors[0] = self.output_tensors[0].view(1)
RuntimeError: shape '[1]' is invalid for input of size 361
```

**Comment by peterjc123** [comment]
设置下环境变量`LOGLEVEL=DEBUG`，然后导出下log试试。或者能把模型发我们调试一下不？

**Comment by peterjc123** [comment]
@steven9046 抱歉，昨天实现的有些问题，现在应该好了，重新安装下试试

**Comment by steven9046** [comment]
好使了:thumbsup::thumbsup::thumbsup:
这项目太棒了！要好好学习一下

**Comment by peterjc123** [comment]
谢谢支持，这个问题我先关了
