### ISSUE TITLE
使用 converter.convert 报错：AssertionError: Model is in training model

### ISSUE THREAD

**Issue by MuMengSunny** [alibaba/TinyNeuralNetwork#64]
您好，当我使用工具转换时，报错：AssertionError: Model is in training model，详细信息如下：
```
2022-04-08 13:56:40.738033: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
Making model...
Load the model from ../float/SESR_S/model/model_best_rep.pt
Traceback (most recent call last):
  File "convert_and_compare.py", line 170, in <module>
    main_worker()
  File "convert_and_compare.py", line 72, in main_worker
    converter.convert()
  File "anaconda3/envs/torchenv/lib/python3.7/site-packages/TinyNeuralNetwork-0.1.0.20220407153809-py3.7.egg/tinynn/converter/base.py", line 357, in convert
    self.init_lowered_module()
  File "anaconda3/envs/torchenv/lib/python3.7/site-packages/TinyNeuralNetwork-0.1.0.20220407153809-py3.7.egg/tinynn/converter/base.py", line 191, in init_lowered_module
    ), 'Model is in training model'
AssertionError: Model is in training model
```
请问这个原因是为何，我应该如何 解决？

**Comment by peterjc123** [comment]
@MuMengSunny 传入模型前，请确保已经执行如下语句 `model.eval()`

**Comment by MuMengSunny** [comment]
我确定执行model.eval()语句了，我的代码如下：
```python
weights_path = '../snapshot/SESR_S/model/model_best.pt'
def main_worker():
    # 模型加载
    global model
    global checkpoint
    model = model.Model(args, checkpoint)
    #ckpt = {}
    checkpoint = torch.load(weights_path, map_location='cpu')
    
    device = torch.device("cpu")
    model.to(device)
    
    model.eval()
    with torch.no_grad():
        graph = torch.jit.trace(model, torch.randn(1, 3, 480, 640))
    # print(graph)

    dummy_input = torch.rand((1, 3, 480, 640))

    output_path = os.path.join(CURRENT_PATH, 'out', 'model.tflite')

    # When converting quantized models, please ensure the quantization backend is set.
    torch.backends.quantized.engine = 'qnnpack'

    # dynamic quantization
    converter = TFLiteConverter(
        graph, dummy_input, output_path, preserve_tensors=True, optimize=GraphOptimizer.ALL_OPTIMIZE,
        # quantize_target_type='int8', hybrid_quantization_from_float=True, hybrid_per_channel=True,
        quantize_target_type='int8',
        # fuse_quant_dequant=True
        )
    converter.convert()
    ......
    
```

**Comment by peterjc123** [comment]
@MuMengSunny 你可以直接传入model，而不用自己trace，如果传入trace的模型的话，一定要重新load一遍，否则会有问题

**Comment by peterjc123** [comment]
@MuMengSunny 另外跟你说一下，单独指定`quantize_target_type='int8'`是不会产生量化的模型的，需要参考qat下面的样例

**Comment by peterjc123** [comment]
Per discussion via DingTalk, the problem is resolved. I'll close this issue.
